### ISSUE TITLE
https://github.com/Azure/azure-powershell/issues/25005#issue-2320358091

### ISSUE THREAD

**Issue by JdaWstripe3** [Azure/autorest.powershell#1370]
**run test**

**encode**
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.powershell/pull/1369
- [ ] https://github.com/Azure/autorest.powershell/pull/1368
- [ ] https://github.com/Azure/autorest.powershell/pull/1366
- [ ] https://github.com/Azure/autorest.powershell/pull/1365
```
